// <auto-generated />
using System;
using LAPTRINHWEB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LAPTRINHWEB.Migrations
{
    [DbContext(typeof(TourDbContext))]
    partial class TourDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LAPTRINHWEB.Models.Accommodation", b =>
                {
                    b.Property<int>("ID_Accommodation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Accommodation");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Accommodation"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Address");

                    b.Property<string>("Description")
                        .HasColumnType("ntext")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Phone");

                    b.Property<int?>("Star_Rating")
                        .HasColumnType("int")
                        .HasColumnName("Star_Rating");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.HasKey("ID_Accommodation");

                    b.ToTable("Accommodations", (string)null);
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Full_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.Booking", b =>
                {
                    b.Property<int>("ID_Booking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Booking");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Booking"));

                    b.Property<DateTime>("Booking_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Booking_Date");

                    b.Property<int>("ID_Tour")
                        .HasColumnType("int")
                        .HasColumnName("ID_Tour");

                    b.Property<string>("Note")
                        .HasColumnType("ntext")
                        .HasColumnName("Note");

                    b.Property<int>("Number_Adults")
                        .HasColumnType("int")
                        .HasColumnName("Number_Adults");

                    b.Property<int>("Number_Children")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Number_Children");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Status");

                    b.Property<decimal>("Total_Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total_Price");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID_Booking");

                    b.HasIndex("Booking_Date");

                    b.HasIndex("ID_Tour");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.Itinerary", b =>
                {
                    b.Property<int>("ID_Itinerary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Itinerary");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Itinerary"));

                    b.Property<int>("Day_Number")
                        .HasColumnType("int")
                        .HasColumnName("Day_Number");

                    b.Property<string>("Description")
                        .HasColumnType("ntext")
                        .HasColumnName("Description");

                    b.Property<int>("ID_Tour")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Title");

                    b.HasKey("ID_Itinerary");

                    b.HasIndex("ID_Tour");

                    b.ToTable("Itineraries", (string)null);
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.ItineraryLocation", b =>
                {
                    b.Property<int>("ID_Item")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Item");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Item"));

                    b.Property<int>("ID_Itinerary")
                        .HasColumnType("int")
                        .HasColumnName("ID_Itinerary");

                    b.Property<int>("ID_Location")
                        .HasColumnType("int")
                        .HasColumnName("ID_Location");

                    b.Property<TimeSpan?>("Visit_Time")
                        .HasColumnType("time")
                        .HasColumnName("Visit_Time");

                    b.HasKey("ID_Item");

                    b.HasIndex("ID_Itinerary");

                    b.HasIndex("ID_Location");

                    b.ToTable("ItineraryLocations", (string)null);
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.Location", b =>
                {
                    b.Property<int>("ID_Location")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Location");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Location"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Address");

                    b.Property<string>("Description")
                        .HasColumnType("ntext")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.HasKey("ID_Location");

                    b.HasIndex("Name");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.Payment", b =>
                {
                    b.Property<int>("ID_Payment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Payment");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Payment"));

                    b.Property<int>("ID_Booking")
                        .HasColumnType("int")
                        .HasColumnName("ID_Booking");

                    b.Property<int>("Method")
                        .HasColumnType("int")
                        .HasColumnName("Method");

                    b.Property<decimal>("Paid_Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Paid_Amount");

                    b.Property<DateTime>("Payment_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Payment_Date");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Status");

                    b.HasKey("ID_Payment");

                    b.HasIndex("ID_Booking");

                    b.HasIndex("Payment_Date");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.Tour", b =>
                {
                    b.Property<int>("ID_Tour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Tour");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Tour"));

                    b.Property<string>("Description")
                        .HasColumnType("ntext")
                        .HasColumnName("Description");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Discount");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("Duration");

                    b.Property<string>("End_Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("End_Location");

                    b.Property<int>("Max_Capacity")
                        .HasColumnType("int")
                        .HasColumnName("Max_Capacity");

                    b.Property<string>("Name_Tour")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name_Tour");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<string>("Start_Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Start_Location");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Status");

                    b.HasKey("ID_Tour");

                    b.HasIndex("Name_Tour");

                    b.HasIndex("Status");

                    b.ToTable("Tours", (string)null);
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.TourAccommodation", b =>
                {
                    b.Property<int>("ID_TourAcc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_TourAcc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_TourAcc"));

                    b.Property<TimeSpan?>("Checkin_Time")
                        .HasColumnType("time")
                        .HasColumnName("Checkin_Time");

                    b.Property<TimeSpan?>("Checkout_Time")
                        .HasColumnType("time")
                        .HasColumnName("Checkout_Time");

                    b.Property<int>("Day_Number")
                        .HasColumnType("int")
                        .HasColumnName("Day_Number");

                    b.Property<int>("ID_Accommodation")
                        .HasColumnType("int")
                        .HasColumnName("ID_Accommodation");

                    b.Property<int>("ID_Tour")
                        .HasColumnType("int")
                        .HasColumnName("ID_Tour");

                    b.Property<int>("Nights")
                        .HasColumnType("int")
                        .HasColumnName("Nights");

                    b.HasKey("ID_TourAcc");

                    b.HasIndex("ID_Accommodation");

                    b.HasIndex("ID_Tour");

                    b.ToTable("TourAccommodations", (string)null);
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.TourGuide", b =>
                {
                    b.Property<int>("ID_Guide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Guide");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Guide"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Email");

                    b.Property<string>("Experience")
                        .HasColumnType("ntext")
                        .HasColumnName("Experience");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FullName");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Phone");

                    b.HasKey("ID_Guide");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("TourGuides", (string)null);
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.TourGuideAssignment", b =>
                {
                    b.Property<int>("ID_Assignment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Assignment");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Assignment"));

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("End_Date");

                    b.Property<int>("ID_Guide")
                        .HasColumnType("int")
                        .HasColumnName("ID_Guide");

                    b.Property<int>("ID_Tour")
                        .HasColumnType("int")
                        .HasColumnName("ID_Tour");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Start_Date");

                    b.HasKey("ID_Assignment");

                    b.HasIndex("ID_Guide");

                    b.HasIndex("ID_Tour");

                    b.HasIndex("Start_Date", "End_Date");

                    b.ToTable("TourGuideAssignments", (string)null);
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.TourImage", b =>
                {
                    b.Property<int>("ID_Image")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Image");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Image"));

                    b.Property<string>("Caption")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Caption");

                    b.Property<int>("ID_Tour")
                        .HasColumnType("int")
                        .HasColumnName("ID_Tour");

                    b.Property<string>("Image_URL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Image_URL");

                    b.HasKey("ID_Image");

                    b.HasIndex("ID_Tour");

                    b.ToTable("TourImages", (string)null);
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.TourTransport", b =>
                {
                    b.Property<int>("ID_TourTransport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_TourTransport");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_TourTransport"));

                    b.Property<TimeSpan?>("Arrival_Time")
                        .HasColumnType("time")
                        .HasColumnName("Arrival_Time");

                    b.Property<int>("Day_Number")
                        .HasColumnType("int")
                        .HasColumnName("Day_Number");

                    b.Property<TimeSpan?>("Departure_Time")
                        .HasColumnType("time")
                        .HasColumnName("Departure_Time");

                    b.Property<string>("From_Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("From_Location");

                    b.Property<int>("ID_Tour")
                        .HasColumnType("int")
                        .HasColumnName("ID_Tour");

                    b.Property<int>("ID_Transport")
                        .HasColumnType("int")
                        .HasColumnName("ID_Transport");

                    b.Property<string>("To_Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("To_Location");

                    b.HasKey("ID_TourTransport");

                    b.HasIndex("ID_Tour");

                    b.HasIndex("ID_Transport");

                    b.ToTable("TourTransports", (string)null);
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.Transportation", b =>
                {
                    b.Property<int>("ID_Transport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Transport");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Transport"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("Capacity");

                    b.Property<string>("Description")
                        .HasColumnType("ntext")
                        .HasColumnName("Description");

                    b.Property<string>("License_Plate")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("License_Plate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("Provider")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Provider");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.HasKey("ID_Transport");

                    b.ToTable("Transportations", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.Booking", b =>
                {
                    b.HasOne("LAPTRINHWEB.Models.Tour", "Tour")
                        .WithMany("Bookings")
                        .HasForeignKey("ID_Tour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LAPTRINHWEB.Models.ApplicationUser", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.Itinerary", b =>
                {
                    b.HasOne("LAPTRINHWEB.Models.Tour", "Tour")
                        .WithMany("Itineraries")
                        .HasForeignKey("ID_Tour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.ItineraryLocation", b =>
                {
                    b.HasOne("LAPTRINHWEB.Models.Itinerary", "Itinerary")
                        .WithMany("ItineraryLocations")
                        .HasForeignKey("ID_Itinerary")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LAPTRINHWEB.Models.Location", "Location")
                        .WithMany("ItineraryLocations")
                        .HasForeignKey("ID_Location")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Itinerary");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.Payment", b =>
                {
                    b.HasOne("LAPTRINHWEB.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("ID_Booking")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.TourAccommodation", b =>
                {
                    b.HasOne("LAPTRINHWEB.Models.Accommodation", "Accommodation")
                        .WithMany("TourAccommodations")
                        .HasForeignKey("ID_Accommodation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LAPTRINHWEB.Models.Tour", "Tour")
                        .WithMany("TourAccommodations")
                        .HasForeignKey("ID_Tour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accommodation");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.TourGuideAssignment", b =>
                {
                    b.HasOne("LAPTRINHWEB.Models.TourGuide", "TourGuide")
                        .WithMany("TourGuideAssignments")
                        .HasForeignKey("ID_Guide")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LAPTRINHWEB.Models.Tour", "Tour")
                        .WithMany("TourGuideAssignments")
                        .HasForeignKey("ID_Tour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");

                    b.Navigation("TourGuide");
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.TourImage", b =>
                {
                    b.HasOne("LAPTRINHWEB.Models.Tour", "Tour")
                        .WithMany("TourImages")
                        .HasForeignKey("ID_Tour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.TourTransport", b =>
                {
                    b.HasOne("LAPTRINHWEB.Models.Tour", "Tour")
                        .WithMany("TourTransports")
                        .HasForeignKey("ID_Tour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LAPTRINHWEB.Models.Transportation", "Transportation")
                        .WithMany("TourTransports")
                        .HasForeignKey("ID_Transport")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");

                    b.Navigation("Transportation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LAPTRINHWEB.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LAPTRINHWEB.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LAPTRINHWEB.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LAPTRINHWEB.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.Accommodation", b =>
                {
                    b.Navigation("TourAccommodations");
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.ApplicationUser", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.Booking", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.Itinerary", b =>
                {
                    b.Navigation("ItineraryLocations");
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.Location", b =>
                {
                    b.Navigation("ItineraryLocations");
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.Tour", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Itineraries");

                    b.Navigation("TourAccommodations");

                    b.Navigation("TourGuideAssignments");

                    b.Navigation("TourImages");

                    b.Navigation("TourTransports");
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.TourGuide", b =>
                {
                    b.Navigation("TourGuideAssignments");
                });

            modelBuilder.Entity("LAPTRINHWEB.Models.Transportation", b =>
                {
                    b.Navigation("TourTransports");
                });
#pragma warning restore 612, 618
        }
    }
}
